# Generated by Django 4.0.3 on 2022-06-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMdb_app', '0006_watchlist_avg_rate_watchlist_total_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rate',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='total_rating',
        ),
    ]
