# Generated by Django 4.0.3 on 2022-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMdb_app', '0007_remove_watchlist_avg_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='no_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
