# Generated by Django 4.0.3 on 2022-06-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMdb_app', '0008_watchlist_avg_rate_watchlist_no_of_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='avg_rate',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='no_of_rating',
        ),
    ]
